version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./employee-todo-backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./employee-todo-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

